from array_list_task.array_list import ArrayList

user_array_list_1 = ArrayList(3)
print("До вставки элементов:")
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")

print("Заполнение списка на массиве элементами:")
user_array_list_1.append(10)
user_array_list_1.append(10)
user_array_list_1.append(10)
user_array_list_1.append(10)
print(user_array_list_1)

print("После вставки элементов:")
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

print("Вставка значения в список на массиве:")
user_array_list_1.append(2)
print("После вставки элемента:")
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print(user_array_list_1)
print()

print("Удаление значения по индексу. Функция должна возвращать удаленное значение:")
print("Список на массиве до удаления:", user_array_list_1)
print("До удаления элемента:")
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print("Возвращенное значение удаленного элеиента:", user_array_list_1.pop(2))
print("Список на массиве после удаления:", user_array_list_1)
print("После удаления элемента:")
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print("Возвращенное значение удаленного элеиента:", user_array_list_1.pop(3))
print("Список на массиве после удаления:", user_array_list_1)
print("После повторного удаления элемента:")
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

print("Проверка метода trim_to_size:")
user_array_list_1.trim_to_size()
print("После применения метода trim_to_size:", user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

print("Проверка метода ensure_capacity:")
user_array_list_1.ensure_capacity(9)
print("После применения метода ensure_capacity:", user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

# Создание второго списка для проверки переопределенных методов __eq__ и __hash__
user_array_list_2 = ArrayList(1)
user_array_list_2.append(10)
user_array_list_2.extend([1, 1, 2, 7, 7, 8, 5, 5, 9, 1, 1, 3, 4, 5, 7])

print("Переопределение метода __eq__:")
print(user_array_list_1 == user_array_list_1)
print()

print("Переопределение метода __hash__:", hash(user_array_list_1))
print()

print("Проверка метода copy:")
print("До копирования:", user_array_list_1)
copied_user_array_list = user_array_list_1.copy()
print(copied_user_array_list)
print(f"Вместимость скопированного списка = {copied_user_array_list.capacity}, "
      f"длина скопированного списка = {len(copied_user_array_list)}")
print("Проверка, что скопировано правильно:")
user_array_list_1[0] = 999999999999
print("Список, который копировали, с изменением:", user_array_list_1)
print("Копия:", copied_user_array_list)
print()

print("Проверка метода delitem:")
print("Список до применеия метода delitem:", user_array_list_1)
del user_array_list_1[-3]
print("Список после применения метода delitem:", user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()
print("Проверка удаления в списке на массиве размера 1:")
user_array_list_3 = ArrayList(3)
user_array_list_3.append(10)
print(f"Вместимость = {user_array_list_3.capacity}, длина списка = {len(user_array_list_3)}")
print("Список на массиве размера 1 до удаления элемента:", user_array_list_3)
del user_array_list_3[0]
print("Список на массиве размера 1 после удаления элемента:", user_array_list_3)
print(f"Вместимость = {user_array_list_3.capacity}, длина списка = {len(user_array_list_3)}")
print()

print("Проверка метода insert:")
print(user_array_list_1)
user_array_list_1.insert(-1, 10000)
print(user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()
user_array_list_1.insert(3, 10000)
print(user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

print("Проверка метода reverse:")
print("Массив до применения метода reverse", user_array_list_1)
user_array_list_1.reverse()
print("Массив после", user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

print("Реализация класса как итератора:")
iterator = iter(user_array_list_1)
print(next(iterator))
print(next(iterator))
print(next(iterator))
print(next(iterator))
print()

print("Проверка slice в __getitem__:")
print(user_array_list_1)
print(user_array_list_1[-1:2:-1])
print(user_array_list_1[0:10:1])
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

user_array_list_1.append(3)
user_array_list_1.append(None)

print("Проверка метода extend:")
print("Список до применения метода extend:", user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
user_array_list_1.extend([1, 1, 2, 7, 7, 8, 5, 5, 9])
print("Список после применения метода extend:", user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()

print("Реализация метода clear:")
print("Список до применения метода clear:", user_array_list_1)
user_array_list_1.clear()
print("Список после применения метода clear:", user_array_list_1)
print(f"Вместимость = {user_array_list_1.capacity}, длина списка = {len(user_array_list_1)}")
print()
